version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn
      - yarn
  pre_build:
    commands:
      - echo pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build && yarn install && yarn build
  post_build:
    commands:
      - echo Build completed on `date`
  

